# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'en-US'
reviews:
  profile: 'chill'
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    auto_pause_after_reviewed_commits: 0
    base_branches:
      - '.*'
chat:
  auto_reply: true
