/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostFormRouteImport } from './routes/_post-form'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as PostFormNewRouteImport } from './routes/_post-form/new'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ApiS3CoverImageRouteImport } from './routes/api/s3.cover-image'
import { Route as ApiOrpcSplatRouteImport } from './routes/api/orpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppUsernamePostSlugRouteImport } from './routes/_app/$username/$postSlug'
import { Route as PostFormUsernamePostSlugEditRouteImport } from './routes/_post-form/$username.$postSlug.edit'

const PostFormRoute = PostFormRouteImport.update({
  id: '/_post-form',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PostFormNewRoute = PostFormNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PostFormRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const ApiS3CoverImageRoute = ApiS3CoverImageRouteImport.update({
  id: '/api/s3/cover-image',
  path: '/api/s3/cover-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrpcSplatRoute = ApiOrpcSplatRouteImport.update({
  id: '/api/orpc/$',
  path: '/api/orpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsernamePostSlugRoute = AppUsernamePostSlugRouteImport.update({
  id: '/$username/$postSlug',
  path: '/$username/$postSlug',
  getParentRoute: () => AppRoute,
} as any)
const PostFormUsernamePostSlugEditRoute =
  PostFormUsernamePostSlugEditRouteImport.update({
    id: '/$username/$postSlug/edit',
    path: '/$username/$postSlug/edit',
    getParentRoute: () => PostFormRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/new': typeof PostFormNewRoute
  '/$username/$postSlug': typeof AppUsernamePostSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/api/s3/cover-image': typeof ApiS3CoverImageRoute
  '/$username/$postSlug/edit': typeof PostFormUsernamePostSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/new': typeof PostFormNewRoute
  '/$username/$postSlug': typeof AppUsernamePostSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/api/s3/cover-image': typeof ApiS3CoverImageRoute
  '/$username/$postSlug/edit': typeof PostFormUsernamePostSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_post-form': typeof PostFormRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_post-form/new': typeof PostFormNewRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$username/$postSlug': typeof AppUsernamePostSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/api/s3/cover-image': typeof ApiS3CoverImageRoute
  '/_post-form/$username/$postSlug/edit': typeof PostFormUsernamePostSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/new'
    | '/$username/$postSlug'
    | '/api/auth/$'
    | '/api/orpc/$'
    | '/api/s3/cover-image'
    | '/$username/$postSlug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/new'
    | '/$username/$postSlug'
    | '/api/auth/$'
    | '/api/orpc/$'
    | '/api/s3/cover-image'
    | '/$username/$postSlug/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_post-form'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_post-form/new'
    | '/_app/'
    | '/_app/$username/$postSlug'
    | '/api/auth/$'
    | '/api/orpc/$'
    | '/api/s3/cover-image'
    | '/_post-form/$username/$postSlug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PostFormRoute: typeof PostFormRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOrpcSplatRoute: typeof ApiOrpcSplatRoute
  ApiS3CoverImageRoute: typeof ApiS3CoverImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_post-form': {
      id: '/_post-form'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PostFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_post-form/new': {
      id: '/_post-form/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof PostFormNewRouteImport
      parentRoute: typeof PostFormRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/s3/cover-image': {
      id: '/api/s3/cover-image'
      path: '/api/s3/cover-image'
      fullPath: '/api/s3/cover-image'
      preLoaderRoute: typeof ApiS3CoverImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orpc/$': {
      id: '/api/orpc/$'
      path: '/api/orpc/$'
      fullPath: '/api/orpc/$'
      preLoaderRoute: typeof ApiOrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$username/$postSlug': {
      id: '/_app/$username/$postSlug'
      path: '/$username/$postSlug'
      fullPath: '/$username/$postSlug'
      preLoaderRoute: typeof AppUsernamePostSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_post-form/$username/$postSlug/edit': {
      id: '/_post-form/$username/$postSlug/edit'
      path: '/$username/$postSlug/edit'
      fullPath: '/$username/$postSlug/edit'
      preLoaderRoute: typeof PostFormUsernamePostSlugEditRouteImport
      parentRoute: typeof PostFormRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppUsernamePostSlugRoute: typeof AppUsernamePostSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppUsernamePostSlugRoute: AppUsernamePostSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PostFormRouteChildren {
  PostFormNewRoute: typeof PostFormNewRoute
  PostFormUsernamePostSlugEditRoute: typeof PostFormUsernamePostSlugEditRoute
}

const PostFormRouteChildren: PostFormRouteChildren = {
  PostFormNewRoute: PostFormNewRoute,
  PostFormUsernamePostSlugEditRoute: PostFormUsernamePostSlugEditRoute,
}

const PostFormRouteWithChildren = PostFormRoute._addFileChildren(
  PostFormRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PostFormRoute: PostFormRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOrpcSplatRoute: ApiOrpcSplatRoute,
  ApiS3CoverImageRoute: ApiS3CoverImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
