/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostFormRouteImport } from './routes/_post-form'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiOgStaticRouteImport } from './routes/api/og-static'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as PostFormNewRouteImport } from './routes/_post-form/new'
import { Route as MainUsernameRouteImport } from './routes/_main/$username'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as ApiS3CoverImageRouteImport } from './routes/api/s3.cover-image'
import { Route as ApiOrpcSplatRouteImport } from './routes/api/orpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as MainUsernameSettingsRouteImport } from './routes/_main/$username_.settings'
import { Route as AppUsernamePostSlugRouteImport } from './routes/_app/$username/$postSlug'
import { Route as MainUsernameSettingsIndexRouteImport } from './routes/_main/$username_.settings.index'
import { Route as PostFormUsernamePostSlugEditRouteImport } from './routes/_post-form/$username.$postSlug.edit'
import { Route as MainUsernameSettingsAccountRouteImport } from './routes/_main/$username_.settings.account'

const PostFormRoute = PostFormRouteImport.update({
  id: '/_post-form',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiOgStaticRoute = ApiOgStaticRouteImport.update({
  id: '/api/og-static',
  path: '/api/og-static',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const PostFormNewRoute = PostFormNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PostFormRoute,
} as any)
const MainUsernameRoute = MainUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => MainRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ApiS3CoverImageRoute = ApiS3CoverImageRouteImport.update({
  id: '/api/s3/cover-image',
  path: '/api/s3/cover-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrpcSplatRoute = ApiOrpcSplatRouteImport.update({
  id: '/api/orpc/$',
  path: '/api/orpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainUsernameSettingsRoute = MainUsernameSettingsRouteImport.update({
  id: '/$username_/settings',
  path: '/$username/settings',
  getParentRoute: () => MainRoute,
} as any)
const AppUsernamePostSlugRoute = AppUsernamePostSlugRouteImport.update({
  id: '/$username/$postSlug',
  path: '/$username/$postSlug',
  getParentRoute: () => AppRoute,
} as any)
const MainUsernameSettingsIndexRoute =
  MainUsernameSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainUsernameSettingsRoute,
  } as any)
const PostFormUsernamePostSlugEditRoute =
  PostFormUsernamePostSlugEditRouteImport.update({
    id: '/$username/$postSlug/edit',
    path: '/$username/$postSlug/edit',
    getParentRoute: () => PostFormRoute,
  } as any)
const MainUsernameSettingsAccountRoute =
  MainUsernameSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => MainUsernameSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$username': typeof MainUsernameRoute
  '/new': typeof PostFormNewRoute
  '/api/og': typeof ApiOgRoute
  '/api/og-static': typeof ApiOgStaticRoute
  '/$username/$postSlug': typeof AppUsernamePostSlugRoute
  '/$username/settings': typeof MainUsernameSettingsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/api/s3/cover-image': typeof ApiS3CoverImageRoute
  '/$username/settings/account': typeof MainUsernameSettingsAccountRoute
  '/$username/$postSlug/edit': typeof PostFormUsernamePostSlugEditRoute
  '/$username/settings/': typeof MainUsernameSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$username': typeof MainUsernameRoute
  '/new': typeof PostFormNewRoute
  '/api/og': typeof ApiOgRoute
  '/api/og-static': typeof ApiOgStaticRoute
  '/$username/$postSlug': typeof AppUsernamePostSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/api/s3/cover-image': typeof ApiS3CoverImageRoute
  '/$username/settings/account': typeof MainUsernameSettingsAccountRoute
  '/$username/$postSlug/edit': typeof PostFormUsernamePostSlugEditRoute
  '/$username/settings': typeof MainUsernameSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_post-form': typeof PostFormRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_main/$username': typeof MainUsernameRoute
  '/_post-form/new': typeof PostFormNewRoute
  '/api/og': typeof ApiOgRoute
  '/api/og-static': typeof ApiOgStaticRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$username/$postSlug': typeof AppUsernamePostSlugRoute
  '/_main/$username_/settings': typeof MainUsernameSettingsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/api/s3/cover-image': typeof ApiS3CoverImageRoute
  '/_main/$username_/settings/account': typeof MainUsernameSettingsAccountRoute
  '/_post-form/$username/$postSlug/edit': typeof PostFormUsernamePostSlugEditRoute
  '/_main/$username_/settings/': typeof MainUsernameSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/$username'
    | '/new'
    | '/api/og'
    | '/api/og-static'
    | '/$username/$postSlug'
    | '/$username/settings'
    | '/api/auth/$'
    | '/api/orpc/$'
    | '/api/s3/cover-image'
    | '/$username/settings/account'
    | '/$username/$postSlug/edit'
    | '/$username/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/$username'
    | '/new'
    | '/api/og'
    | '/api/og-static'
    | '/$username/$postSlug'
    | '/api/auth/$'
    | '/api/orpc/$'
    | '/api/s3/cover-image'
    | '/$username/settings/account'
    | '/$username/$postSlug/edit'
    | '/$username/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_main'
    | '/_post-form'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_main/$username'
    | '/_post-form/new'
    | '/api/og'
    | '/api/og-static'
    | '/_app/'
    | '/_app/$username/$postSlug'
    | '/_main/$username_/settings'
    | '/api/auth/$'
    | '/api/orpc/$'
    | '/api/s3/cover-image'
    | '/_main/$username_/settings/account'
    | '/_post-form/$username/$postSlug/edit'
    | '/_main/$username_/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  PostFormRoute: typeof PostFormRouteWithChildren
  ApiOgRoute: typeof ApiOgRoute
  ApiOgStaticRoute: typeof ApiOgStaticRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOrpcSplatRoute: typeof ApiOrpcSplatRoute
  ApiS3CoverImageRoute: typeof ApiS3CoverImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_post-form': {
      id: '/_post-form'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PostFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/og-static': {
      id: '/api/og-static'
      path: '/api/og-static'
      fullPath: '/api/og-static'
      preLoaderRoute: typeof ApiOgStaticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_post-form/new': {
      id: '/_post-form/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof PostFormNewRouteImport
      parentRoute: typeof PostFormRoute
    }
    '/_main/$username': {
      id: '/_main/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof MainUsernameRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/s3/cover-image': {
      id: '/api/s3/cover-image'
      path: '/api/s3/cover-image'
      fullPath: '/api/s3/cover-image'
      preLoaderRoute: typeof ApiS3CoverImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orpc/$': {
      id: '/api/orpc/$'
      path: '/api/orpc/$'
      fullPath: '/api/orpc/$'
      preLoaderRoute: typeof ApiOrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/$username_/settings': {
      id: '/_main/$username_/settings'
      path: '/$username/settings'
      fullPath: '/$username/settings'
      preLoaderRoute: typeof MainUsernameSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_app/$username/$postSlug': {
      id: '/_app/$username/$postSlug'
      path: '/$username/$postSlug'
      fullPath: '/$username/$postSlug'
      preLoaderRoute: typeof AppUsernamePostSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_main/$username_/settings/': {
      id: '/_main/$username_/settings/'
      path: '/'
      fullPath: '/$username/settings/'
      preLoaderRoute: typeof MainUsernameSettingsIndexRouteImport
      parentRoute: typeof MainUsernameSettingsRoute
    }
    '/_post-form/$username/$postSlug/edit': {
      id: '/_post-form/$username/$postSlug/edit'
      path: '/$username/$postSlug/edit'
      fullPath: '/$username/$postSlug/edit'
      preLoaderRoute: typeof PostFormUsernamePostSlugEditRouteImport
      parentRoute: typeof PostFormRoute
    }
    '/_main/$username_/settings/account': {
      id: '/_main/$username_/settings/account'
      path: '/account'
      fullPath: '/$username/settings/account'
      preLoaderRoute: typeof MainUsernameSettingsAccountRouteImport
      parentRoute: typeof MainUsernameSettingsRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppUsernamePostSlugRoute: typeof AppUsernamePostSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppUsernamePostSlugRoute: AppUsernamePostSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainUsernameSettingsRouteChildren {
  MainUsernameSettingsAccountRoute: typeof MainUsernameSettingsAccountRoute
  MainUsernameSettingsIndexRoute: typeof MainUsernameSettingsIndexRoute
}

const MainUsernameSettingsRouteChildren: MainUsernameSettingsRouteChildren = {
  MainUsernameSettingsAccountRoute: MainUsernameSettingsAccountRoute,
  MainUsernameSettingsIndexRoute: MainUsernameSettingsIndexRoute,
}

const MainUsernameSettingsRouteWithChildren =
  MainUsernameSettingsRoute._addFileChildren(MainUsernameSettingsRouteChildren)

interface MainRouteChildren {
  MainUsernameRoute: typeof MainUsernameRoute
  MainUsernameSettingsRoute: typeof MainUsernameSettingsRouteWithChildren
}

const MainRouteChildren: MainRouteChildren = {
  MainUsernameRoute: MainUsernameRoute,
  MainUsernameSettingsRoute: MainUsernameSettingsRouteWithChildren,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface PostFormRouteChildren {
  PostFormNewRoute: typeof PostFormNewRoute
  PostFormUsernamePostSlugEditRoute: typeof PostFormUsernamePostSlugEditRoute
}

const PostFormRouteChildren: PostFormRouteChildren = {
  PostFormNewRoute: PostFormNewRoute,
  PostFormUsernamePostSlugEditRoute: PostFormUsernamePostSlugEditRoute,
}

const PostFormRouteWithChildren = PostFormRoute._addFileChildren(
  PostFormRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  PostFormRoute: PostFormRouteWithChildren,
  ApiOgRoute: ApiOgRoute,
  ApiOgStaticRoute: ApiOgStaticRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOrpcSplatRoute: ApiOrpcSplatRoute,
  ApiS3CoverImageRoute: ApiS3CoverImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
